name: Windows Build & Test

defaults:
  run:
    shell: bash
    working-directory: C:\TES3MP-mumble

on:
  push:
    branches:
      - 'master'
      - 'fix/*'
      - 'feat/*'
  pull_request:
    branches: [ master ]
    types:
      - created
  workflow_dispatch:

env:
  BUILD_TYPE: Release
  GIT_TERMINAL_PROMPT: 0

jobs:
  Windows:
    strategy:
      matrix:
        build_type: [ Release ]
    runs-on: windows-2019

    steps:
      - name: Clone
        working-directory: C:\
        run: |
          git clone https://github.com/FakeSalamander/TES3MP-mumble.git
          cd TES3MP-mumble
          git checkout ${{ github.head_ref }}



      - name: Install Building Dependencies
        if: steps.cache-WinDeps.outputs.cache-hit != 'true'
        run: |
          curl -o CrabNet.7z -L https://github.com/DreamWeave-MP/CrabNet/releases/download/Stable-CI/CrabNet-${{ runner.os }}-${{ matrix.BUILD_TYPE }}.7z
          7z x -y CrabNet.7z -oextern/raknet
          CI/before_script.msvc.sh  -V -N -k -p Win64 -v 2019

      - name: Configure
        if: steps.cache-WinDeps.outputs.cache-hit == 'true'
        run: |
          CI/before_script.msvc.sh  -V -N -k -p Win64 -v 2019 -d -e

      - name: Build
        run: |
          cd MSVC2019_64_Ninja
          source activate_msvc.sh
          ninja -f build-${{ matrix.BUILD_TYPE }}.ninja


      - name: Package
        run: |
          CI/make_package.msvc.sh ${{ matrix.BUILD_TYPE }}

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          path: C:/TES3MP-mumble/tes3mp-build
          name: tes3mp-mumbe_windows-${{ matrix.BUILD_TYPE }}
